<?xml version="1.0" encoding="utf-8"?><Database Name="msdb1849" Class="marketDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=lugh4.it.nuigalway.ie;Initial Catalog=msdb1849;Persist Security Info=True;User ID=msdb1849" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="msdb1849ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LWA" Member="LWAs">
    <Type Name="LWA">
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Run_Type" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Lwa" Member="Lwa1" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="SevenDayLWA" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MaxSMP" Member="MaxSMPs">
    <Type Name="MaxSMP">
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Run_Type" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaxSMP" Member="MaxSMP1" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="SevenDayMaxSMP" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MinSMP" Member="MinSMPs">
    <Type Name="MinSMP">
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Run_Type" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MinSMP" Member="MinSMP1" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="SevenDayMinSMP" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Shadow_SMP" Member="Shadow_SMPs">
    <Type Name="Shadow_SMP">
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Run_Type" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SMP" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="ShadowPrice" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SMP_Load" Member="SMP_Loads">
    <Type Name="SMP_Load">
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Run_Type" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SMP" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="SystemLoad" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>